### ISSUE TITLE
5.25ea1 not usable

### ISSUE THREAD

**Issue by andrm** [OpenHFT/Chronicle-Queue#1482]
It seems there is an artifact missing in repo.maven.apache.org:
```
$ ./gradlew  clean build
> Task :extractIncludeProto FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':extractIncludeProto'.
> Could not resolve all files for configuration ':compileProtoPath'.
   > Could not find net.openhft:compiler:2.25.0.
     Searched in the following locations:
       - file:/home/am7c7/.m2/repository/net/openhft/compiler/2.25.0/compiler-2.25.0.pom
       - https://repo.maven.apache.org/maven2/net/openhft/compiler/2.25.0/compiler-2.25.0.pom
     Required by:
         project : > net.openhft:chronicle-queue:5.25ea1 > net.openhft:chronicle-wire:2.25ea1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.3/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 1s
2 actionable tasks: 2 executed
```

**Comment by andrm** [comment]
ea0 works.

**Comment by tgd** [comment]
@andrm thanks for raising this report - we will look into this and be back with next steps.

**Comment by tgd** [comment]
Hi Andreas

The latest release of Queue refers to a version of the OpenHFT compiler which is not available on maven central. We will re-release in order to resolve this issue. Apologies for the friction caused and thanks for letting us know you faced issues with this.

In the meantime you can use the below workaround to exclude the OpenHFT compiler dependency that is brought in transitively via the queue dependency and then bring in the correct version explicitly. The example below is using the Gradle Kotlin DSL:

```kotlin
dependencies {
    implementation("net.openhft:chronicle-queue:5.25ea1") {
        exclude("net.openhft", "compiler")
    }
    implementation("net.openhft:compiler:2.25ea0")
}
```

@andrm please can you let us know if this resolves your issue?

Maven users should be able to specify our bom directly in the `<dependencyManagement>` section of their pom. You can find the latest chronicle-boms here: https://central.sonatype.com/artifact/net.openhft/chronicle-bom/overview. It _should_ also be possible use the bom approach in Gradle.

**Comment by andrm** [comment]
yes, it works, thanks!

**Comment by tgd** [comment]
Excellent - thanks for confirming
