### ISSUE TITLE
Bundles not loaded on Karaf (OSGI)

### ISSUE THREAD

**Issue by danielshrem** [OpenHFT/Chronicle-Queue#291]
Hi,
i came across these errors while trying to load the chronicle-queue and all its dependencies to Karaf.
i keep getting errors on the following bundles:
1. chronicle-core-1.7.2
2. chronicle-core-1.7.6
3. affinity-3.0.5

errors were all due to unresolved requirement, all relate to sun.xxx.xx
for example on core bundle
_"Unresolved requirement: Import-Package: net.openhft.affinity; version="[3.0.0,4.0.0)"; resolution:="optional"
 Unresolved requirement: Import-Package: sun.nio.ch"_

i managed to resolve the issue by manually editing the above jars manifest files (see attached example)
, so all sun.xxx are optional as well, but i don't know if this is correct or not.
[MANIFEST.MF.txt](https://github.com/OpenHFT/Chronicle-Queue/files/454003/MANIFEST.MF.txt)

also i made sure that karaf has sun.\* in its bootdelegation config so it should be resolved OK.
these errors could be recreated easily by just throwing chronicle jars in to karaf's deploy folder.
i am running with this configuration: Windows 7 (sp1), jdk1.8.0_92, apache-karaf-4.0.4, chronicle-queue 4.5.13
feel free to contact if anything else is need.

**Comment by peter-lawrey** [comment]
Hello,
  The optional library shouldn't be required and I don't believe we can
enable the use of sun.* from the library. It has to be changed in your
configuration.

Regards, Peter.

**Comment by amichair** [comment]
I've also encountered this issue, and found 3 solutions:

1. Remove the offending JRE-supplied package imports (sun.* and com.sun.* ) from the Chronicle jars, since they are included in Karaf's default org.osgi.framework.bootdelegation configuration. This causes these classes to be loaded via the system classloader (just like java.* etc.) and not require any bundle wirings or imports. I don't know why Karaf doesn't just treat these as resolved imports, since all bundles can see them.

2. Add the missing JRE packages to the jre.properties configuration, so they are exported by the system bundle and resolved normally by the Chronicle bundles.

3. Add the missing JRE packages to the org.osgi.framework.system.packages.extra configuration, so they are exported by the system bundle and resolved normally by the Chronicle bundles. I think this is preferred over changing jre.properties.

Seeing that Chronicle uses packages which are supplied by the JRE (only works on Sun/Oracle I guess?) and not available as separate bundles, and this does not work using the default configuration, I think that this should at least be documented somewhere, if not solved somehow.

**Comment by cgorantla** [comment]
If you are using karaf as osgi  container,  adding following property to custom.properties would resolve the dependencies.

org.osgi.framework.system.packages.extra=sun.misc,\
                   sun.nio.ch,\
                   com.sun.jna,\
                   com.sun.jna.ptr

**Comment by RobAustin** [comment]
closing this issue as I feel that this has been answered by @cgorantla and its 2 years old.
