### ISSUE TITLE
Possible file descriptor leak

### ISSUE THREAD

**Issue by amichair** [OpenHFT/Chronicle-Queue#306]
We've had some trouble with cycled files that are not being released. In a heap dump I see a ThreadLocal with SCQIndexing$LongArrayValuesHolder -> BinaryLongArrayReference -> MappedBytes -> MappedFile -> RandomAccessFile (and channel) holding on to a file that was cycled out and (I think) should have been released but isn't. The MappedFile refCount is at 3, although there are 9 references to the MappedFile (including 7 MappedBytes instances).

When should a file be ultimately released? Will the WeakReference in #305 and elsewhere dispose of the object reference but leave the file open? Does a reference count need to be released first? It's also possible that there's a ref count leak regardless of the ThreadLocal, or that I'm simply doing something wrong or misunderstanding the file descriptor management here...

As @peter-lawrey mentioned in #305, at the very least there should be tests for this.

**Comment by peter-lawrey** [comment]
There should be tests.

The reference count is intended to provide deterministic clean up. If the
objects are discarded first they will be cleaned up by the GC, at some
point.

We are very busy with paying clients until mid December so I am not sure
when will be able to look at this in detail. I am sorry we don't have spare
resources at the moment.

Regards, Peter.

On 7 Nov 2016 18:50, "amichair" <notifications@github.com> wrote:

We've had some trouble with cycled files that are not being released. In a
heap dump I see a ThreadLocal with SCQIndexing$LongArrayValuesHolder ->
BinaryLongArrayReference -> MappedBytes -> MappedFile -> RandomAccessFile
(and channel) holding on to a file that was cycled out and (I think) should
have been released but isn't. The MappedFile refCount is at 3, although
there are 9 references to the MappedFile (including 7 MappedBytes
instances).

When should a file be ultimately released? Will the WeakReference in #305
<https://github.com/OpenHFT/Chronicle-Queue/issues/305> and elsewhere
dispose of the object reference but leave the file open? Does a reference
count need to be released first? It's also possible that there's a ref
count leak regardless of the ThreadLocal, or that I'm simply doing
something wrong or misunderstanding the file descriptor management here...

As @peter-lawrey <https://github.com/peter-lawrey> mentioned in #305
<https://github.com/OpenHFT/Chronicle-Queue/issues/305>, at the very least
there should be tests for this.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/OpenHFT/Chronicle-Queue/issues/306>, or mute the thread

**Comment by amichair** [comment]
I think I found a leak, unrelated to thread locals: StoreAppender holds a WireStore which is set in setCycle2(), which internally holds mappedBytes/mappedFile references. These are reference-counted when created, but are not released. Actually, the store itself is not released (which would release the mapped file) - it is released when a new one is created in setCycle2(), but shouldn't it also release the store (if not null) in close()?

**Comment by amichair** [comment]
Also if you look at all usages of storeForCycle(), which increases the returned store's reference count, you'll see that it is not properly released in all code paths.

**Comment by peter-lawrey** [comment]
You are right that when a resource is reserved, it should be released on a
close.

Can this identify which code paths for which a storeForCycle() s not
released?

**Comment by amichair** [comment]
btw, regarding calling release in StoreAppender.close() (two comments up), note that it may seem like this is unnecessary because SingleChronicleQueue.close() calls pool.close() which invokes release on all the stores... however this only does a single release on the store, which only decrements the reference count but doesn't actually close it until the count reaches zero, which won't happen if there was more than one StoreAppender (multiple threads) acquiring the store.

**Comment by peter-lawrey** [comment]
That is is part deliberate. You can't close a store while a thread is
holding it. Access a native release which has actually been released will
crash the JVM.

**Comment by amichair** [comment]
As for storeForCycle(), glancing through the usages: in SingleChronicleQueue.dump it gets the store but doesn't release it. Same in SingleChronicleQueue.exceptsPerCycle - it just uses it locally without releasing. The third usage is in StoreAppender.setCycle2() as mentioned above. The others look ok... but the code is a bit hard for me to follow, so you should probably double check everything :-)

**Comment by amichair** [comment]
I don't follow the comment about thread/native/crash. If every acquire is paired with a release, then it should only be closed when refcount reaches 0, i.e. when it is no longer used by anything, no?

**Comment by peter-lawrey** [comment]
On paired releases, I agree. However, it means that when you call close()
there may be threads still using the underlying stores do it can't actually
be closed until they release the resources.

The code has been double checked by a few people. This doesn't mean there
isn't bug and fresh eyes is very helpful.

**Comment by amichair** [comment]
What you describe sounds to me like the correct behavior, no? Currently it looks like they simply never really get closed, because a few releases are missing, so the ref count never reaches zero and the cleanup code doesn't run. The close methods currently just call release methods of nested instances, and things only really get cleaned up when the ref counts reach zero.

To clarify, there seem to be issues both with the mapped file references and the store references themselves (we've seen both files staying in use, and onReleased not being called due to stores not being released). The former may be caused by the latter.

**Comment by amichair** [comment]
@peter-lawrey Could you please clarify where this stands? I'm not sure which of the issues mentioned in this thread you acknowledge and will fix, which you think are not bugs, and which you intend to investigate further...

Also, if anything I wrote is unclear, I can try to clarify.

**Comment by peter-lawrey** [comment]
This month is very busy for us. All of it should be reviewed again but I
don't think we will have a chance to look at it until December.

**Comment by amichair** [comment]
After applying PR #314 there is still the issue of StoreAppenders which are never closed (even now that close actually releases the store).

To be more precise, they are all added to the queue's closers list (which in itself might keep growing as weak references are disposed and new appenders created) and the closers are only actually closed when the queue is closed, which is generally when the application is shut down.

So the appender and all of its related resources (like the store, files, etc.) remain in use until shutdown... and that's a leak.

**Comment by peter-lawrey** [comment]
There is an assumption that you won't discard many of these
Appenders/Tailers over the life of the queue, however I take your point.

https://github.com/OpenHFT/Chronicle-Queue/issues/315

**Comment by amichair** [comment]
Given the WeakReferences, this can happen even more often than the user might expect.

But more importantly, even if it's just one unused appender that lingers around... it means the store isn't released, which means the onReleased callback might not be called, and the file remains in use and can't be deleted if necessary as the cycles roll, and the disk fills up, and... (that's actually what triggered our investigation of this issue in the first place!)

It's better release all resources when they are no longer needed :-)

**Comment by scottkidder** [comment]
This should be closed in favor of #315 and #357

**Comment by dpisklov** [comment]
Fixed in #357
