### ISSUE TITLE
BUG: appender -> tailer synchronization contract

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [OpenHFT/Chronicle-Queue#317]
1) as mentioned on [stack overflow](http://stackoverflow.com/questions/41429878/chronicle-queue-events-listener):
 `appender.doc.close()` should make entry visible for the following `tailer.doc.isPresent()`

2) this [little test](https://gist.github.com/Andrei-Pozolotin/ff912744323d3dbb758b890e81365463#file-main-java) shows that currently [contract fails](https://gist.github.com/Andrei-Pozolotin/ff912744323d3dbb758b890e81365463#file-main-log) intermittently

**Comment by peter-lawrey** [comment]
This is an interesting comment. The test only really applies for the
readingDocument(), the isPresent is determined on this method there would
need to be a significant code change to alter this.

How important is it that the isPresent be an active test on that line of
code?

public DocumentContext readingDocument(boolean includeMetaData) {
    try {
        if (context.present(next(includeMetaData))) {
            assert wire().startUse();
            return context;
        }
    } catch (StreamCorruptedException e) {
        throw new IllegalStateException(e);
    } catch (UnrecoverableTimeoutException notComplete) {
        // so treat as empty.
    }
    return NoDocumentContext.INSTANCE;  // << once tested, this is not
tested again.
}

**Comment by peter-lawrey** [comment]
I don't think the check on readingDocument or isPresent matters here
actually.

Since you read all the pending messages and then wait for a signal, after a
signal is triggered, there is no guarantee there will be any messages
waiting.

consider

T1: writes a message
T2: reads a message
T2: waits as there is no more.
T1: signals
T2: wakes from signal.
T2: checks for next message but there is none.
T1: writes a message.

**Comment by Andrei-Pozolotin** [comment]
1) re: "How important is it that the isPresent be an active test" - now important is only clarity; if there is no `appender -> tailer synchronization contract`, that is fine as well, will use spin/pause.

2) re: "I don't think the check on readingDocument or isPresent matters here
actually." - you are right, the test is in error; please confirm there "should be a contract" indeed, and perhaps there is a test for that in the repo already?

**Comment by peter-lawrey** [comment]
The problem we have is that a thread can be interrupted for 5 ms - 50 ms by
the scheduler for no apparent reason, so there is no way to guarantee in a
second thread to immediately see anything the first thread is doing because
you don't know it has been running.

What we try to do instead is time the latency from write to read and keep
this to a minimum, as consistently as possible ideally tested with isolated
CPUs to minimise scheduling jitter, for a fixed throughput. If you use a
maximum throughput you exhaust the resources of your CPU socket pretty
quickly.

**Comment by Andrei-Pozolotin** [comment]
in this case it would help to document that clearly, i.e.
```
Q: is there an event listener for appender -> tailer notification?

A: there is no explicit appender -> tailer notification/synchronization 
mechanism. tailer must always rely on spin/pause approach. this is due to ...
```

**Comment by peter-lawrey** [comment]
A good suggestion.

**Comment by peter-lawrey** [comment]
I have added a section to the end of the README with an example of how you can use the Pauser.

**Comment by Andrei-Pozolotin** [comment]
thank you
