### ISSUE TITLE
lazyIndexing support dropped

### ISSUE THREAD

**Issue by scottkidder** [OpenHFT/Chronicle-Queue#327]
What is the status of lazyIndexing support as the interface methods have been removed?

**Comment by peter-lawrey** [comment]
AFAIK it wasn't being used by us. If you were using it we can add it back.

On 13 Jan 2017 22:42, "Scott Kidder" <notifications@github.com> wrote:

What is the status of lazyIndexing support as the interface methods have
been removed?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/OpenHFT/Chronicle-Queue/issues/327>, or mute the thread
