### ISSUE TITLE
Race condition when starting many tailers against one queue

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#377]
Please find attached a very ugly test - it may fail immediately or could take 10s seconds to barf.

If you run with `-Dorg.slf4j.simpleLogger.defaultLogLevel=trace` you will see
`[pool-2-thread-16] DEBUG net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer - moveToIndex: 4400 ffffffff
`
just before
`java.lang.IllegalStateException: NOT_REACHED index: 4400ffffffff
`
and this is because
`long sequenceNumber = store.lastSequenceNumber(this);`
in `net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts.StoreTailer#approximateLastIndex` returns -1. Haven't had the time to dive in further.

```
package net.openhft.chronicle.queue;

import net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder;
import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.util.Arrays;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicInteger;

import static org.junit.Assert.assertEquals;

/**
 * Created by jerry on 27/08/2017.
 */
public class TestTailerToEndThreadSafe2 {
    private static final Logger LOG = LoggerFactory.getLogger(TestTailerToEndThreadSafe2.class);

    @Test
    public void testToEnd() throws java.io.IOException, InterruptedException, ExecutionException, TimeoutException {

        final long MIN_VALUE = 0x8000000000000000L;
        final long MAX_VALUE = 0x7fffffffffffffffL;
        long i1 = 0x43ffffffffffL;

        for (int rep = 0; rep < 1000; rep++) {
            final File path = DirectoryUtils.tempDir("cq");
            try (final ChronicleQueue rqueue = SingleChronicleQueueBuilder.binary(path)
                    .testBlockSize()
                    .build()) {
                final int numThreads = 1000, writes = 100;
                final ExecutorService executorService = Executors.newFixedThreadPool(numThreads);
                final AtomicInteger errors = new AtomicInteger();

                TailerState[] states = new TailerState[numThreads];
                for (int threadId = 0; threadId < numThreads; threadId++) {
                    final int finalThreadId = threadId;
                    executorService.submit(() -> {
                        try {
                            if (finalThreadId == 0) {
                                final ExcerptAppender appender = rqueue.acquireAppender();
                                for (int i = 0; i < writes; i++) {
                                    appender.writeText("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
                                }
                            } else {
                                final ExcerptTailer tailer = rqueue.createTailer();
                                tailer.toEnd();
                                states[finalThreadId] = tailer.state();
                            }
                        } catch (Throwable t) {
                            errors.incrementAndGet();
                            LOG.error("", t);
                        }
                    });
                }

                executorService.awaitTermination(1000, TimeUnit.MILLISECONDS);
                // .. UNINITIALISIED.... then FOUND_CYCLE...
                System.out.println(Arrays.toString(states));
                assertEquals(0, errors.get());
            }
        }
    }
}
```

**Comment by peter-lawrey** [comment]
Thank you.

On 18 Sep. 2017 02:00, "JerryShea" <notifications@github.com> wrote:

Please find attached a very ugly test - it may fail immediately or could
take 10s seconds to barf.

If you run with -Dorg.slf4j.simpleLogger.defaultLogLevel=trace you will see
[pool-2-thread-16] DEBUG net.openhft.chronicle.queue.impl.single.
SingleChronicleQueueExcerpts$StoreTailer - moveToIndex: 4400 ffffffff
just before
java.lang.IllegalStateException: NOT_REACHED index: 4400ffffffff
and this is because
long sequenceNumber = store.lastSequenceNumber(this);
in net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts.
StoreTailer#approximateLastIndex returns -1. Haven't had the time to dive
in further.

package net.openhft.chronicle.queue;

import net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder;
import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.util.Arrays;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicInteger;

import static org.junit.Assert.assertEquals;

/**
 * Created by jerry on 27/08/2017.
 */
public class TestTailerToEndThreadSafe2 {
    private static final Logger LOG =
LoggerFactory.getLogger(TestTailerToEndThreadSafe2.class);

    @Test
    public void testToEnd() throws java.io.IOException,
InterruptedException, ExecutionException, TimeoutException {

        final long MIN_VALUE = 0x8000000000000000L;
        final long MAX_VALUE = 0x7fffffffffffffffL;
        long i1 = 0x43ffffffffffL;

        for (int rep = 0; rep < 1000; rep++) {
            final File path = DirectoryUtils.tempDir("cq");
            try (final ChronicleQueue rqueue =
SingleChronicleQueueBuilder.binary(path)
                    .testBlockSize()
                    .build()) {
                final int numThreads = 1000, writes = 100;
                final ExecutorService executorService =
Executors.newFixedThreadPool(numThreads);
                final AtomicInteger errors = new AtomicInteger();

                TailerState[] states = new TailerState[numThreads];
                for (int threadId = 0; threadId < numThreads; threadId++) {
                    final int finalThreadId = threadId;
                    executorService.submit(() -> {
                        try {
                            if (finalThreadId == 0) {
                                final ExcerptAppender appender =
rqueue.acquireAppender();
                                for (int i = 0; i < writes; i++) {

appender.writeText("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
                                }
                            } else {
                                final ExcerptTailer tailer =
rqueue.createTailer();
                                tailer.toEnd();
                                states[finalThreadId] = tailer.state();
                            }
                        } catch (Throwable t) {
                            errors.incrementAndGet();
                            LOG.error("", t);
                        }
                    });
                }

                executorService.awaitTermination(1000, TimeUnit.MILLISECONDS);
                // .. UNINITIALISIED.... then FOUND_CYCLE...
                System.out.println(Arrays.toString(states));
                assertEquals(0, errors.get());
            }
        }
    }
}

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/OpenHFT/Chronicle-Queue/issues/377>, or mute the thread

**Comment by epickrram** [comment]
I think this is a duplicate of #378, which I've just fixed. Running your test locally passes after ~10 repetitions. Can you re-test and see if you still see errors please?

**Comment by JerryShea** [comment]
Yep - fixed - thanks Mark
