### ISSUE TITLE
Add Table of < String, Long Value >

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#379]
for user that wish to store extra meta data into the chronicle queue, please implement as a linked list of meta data, with an API something like:

longValue get(string); // which will create it if it does not exist

changing the <long value> will set a long in the chronicle queue

**Comment by peter-lawrey** [comment]
Most likely these values will need to be in a file of their own so they can
still exist after the queue files roll. We would need a tool to dump the
contents.

On 21 Sep. 2017 16:16, "Rob Austin" <notifications@github.com> wrote:

for user that wish to store extra meta data into the chronicle queue,
please implement as a linked list of meta data, with an API something like:

get(); // which will create it if it does not exist

changing the will set a long in the chronicle queue

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/OpenHFT/Chronicle-Queue/issues/379>, or mute the thread

**Comment by RobAustin** [comment]
if we are going to do that why not just use a chronicle map ? as meta data anyway is not replicated

**Comment by peter-lawrey** [comment]
Pulling in the whole of map for such a simple use case feels like overkill
however many users will has map as well.
It means we are making queue dependant on map and everything it depends on.

**Comment by peter-lawrey** [comment]
We should be able to create a super simple binary yaml file to store this
data.

On 22 September 2017 at 16:43, Peter Lawrey <peter.lawrey@chronicle.software
> wrote:

> Pulling in the whole of map for such a simple use case feels like overkill
> however many users will has map as well.
> It means we are making queue dependant on map and everything it depends on.
>
> On 22 September 2017 at 10:01, Rob Austin <notifications@github.com>
> wrote:
>
>> if we are going to do that why not just use a chronicle map ? as meta
>> data anyway is not replicated
>>
>> > On 22 Sep 2017, at 06:53, Peter Lawrey <notifications@github.com>
>> wrote:
>> >
>> > Most likely these values will need to be in a file of their own so they
>> can
>> > still exist after the queue files roll. We would need a tool to dump the
>> > contents.
>> >

**Comment by RobAustin** [comment]
@peter-lawrey should it replicated via TCP/IP ?

**Comment by peter-lawrey** [comment]
Good point. I think if we update LongValue directly Map replication won't
work anyway as it currently is.
For some use cases it might be useful but others perhaps not desirable.
