### ISSUE TITLE
TSQueueLock held for too long.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Queue#456]
Please check that the lock is only acquired only for the purpose of key creation and no longer.  Holding the lock longer increases the risk that the process will die holding the lock (and hurt performance)

**Comment by NickWard** [comment]
Looks like it is acquired in software.chronicle.enterprise.queue.replication.SourceReplicationHandler and software.chronicle.enterprise.queue.QueueSourceReplicationHandler and is held for a long time. Acquiring an appender checks this, so maybe the lock is being acquired on the wrong sub-queue?

**Comment by dpisklov** [comment]
Queue Lock is there to facilitate Sink to Source replication. The lock must be held for as long as Sink is sending data to the Source, until Source received EOS (end of stream) packet. It's impossible to reduce the time it is held without rendering it useless, and writing to the queue must be blocked while Sink is sending data, otherwise the queue will be corrupted from replication perspective (i.e. data will be reordered).

**Comment by dpisklov** [comment]
Added timeout and autorecovery. Issue no longer exists
