### ISSUE TITLE
Support for reading/writing nio's ByteBuffer

### ISSUE THREAD

**Issue by erikvanoosten** [OpenHFT/Chronicle-Queue#47]
I am using Netty to receive data which I want to directly dump into a journal. I would be great if Java-Chronicle can do zero-copy writing. For this Java-Chronicle would need to support writing (and preferably also reading) nio's ByteBuffer directly.

**Comment by pjulien** [comment]
> This is possible, but involves some hacking of ByteBuffer

For my use case, I would have to say that being able to get back a ``File``, a position and a counter would be the most usable for me.  Would allow easier integration with various networking toolkits no matter what protocol they support.

I would use this with Netty's ``DefaultFileRegion`` definitely but I have to deal with HTTP also.  This gives me the flexibility of sending excerpts off to other places without reloading them at all in the process, not even an ``mmap``. 

In this use case, I'm sending data somewhat after the fact, when the data is no longer hot and has been unmapped for maybe an hour or so.

Hope this comment is useful.

**Comment by kd8azz** [comment]
I'm interested in this as well.  My use case is moving data from an OpenCL context on the graphics card into Chronicle, preferably with only one copy, rather than two.

**Comment by peter-lawrey** [comment]
The safest option for accessing data across machines is to use the index.
There are some modes of replication were you don't get exactly the same
data arrangement eg because you have applied a filter to select which data
you want replicated. Using an index should always work.

However you can obtain the address() of a Bytes in memory assuming it is
off heap. For access to say OpenCV.

Regards,
   Peter.

**Comment by peter-lawrey** [comment]
Queue v4 supports wrapping a ByteBuffer for zero copy.
