### ISSUE TITLE
Underlying ByteBuffer does not reflect Bytes state

### ISSUE THREAD

**Issue by abysas** [OpenHFT/Chronicle-Queue#578]
`ByteBuffer` obtained through `Bytes#underlyingObject()` does not reflect the the state of `Bytes` instance:  `ByteBuffer#limit()`  does not match the `Bytes#length()`. Here is the Unit test illustrating the issue:

```
    @Test
    void testUnderlyingBuffer() {
        byte[] data = new byte[16];
        Bytes<ByteBuffer> elasticByteBuffer = Bytes.elasticByteBuffer();
        elasticByteBuffer.write(data);
        ByteBuffer byteBuffer = elasticByteBuffer.underlyingObject();
        Assertions.assertEquals(byteBuffer.limit(), elasticByteBuffer.length());
    }
```
This test fails with error:
```
org.opentest4j.AssertionFailedError: 
Expected :256
Actual   :16
```
Chronicle Queue version used: 5.17.3

**Comment by dpisklov** [comment]
This is by design.
We don't use Java API to write to bytebuffer, instead we write directly to the (on heap or off heap) memory for speed, and it is deliverate decision not to tr to update underlying buffer's state.
User can always do this if direct interaction with ByteBuffer object is needed, e.g. (from TcpEventHandler class in Chronicle-Network project):
```
        @Nullable ByteBuffer inBB = inBBB.underlyingObject();
        inBB.position((int) inBBB.readPosition());
        inBB.limit((int) inBBB.readLimit());
        inBB.compact();
        inBBB.readPosition(0);
        inBBB.readLimit(inBB.remaining());
```
