### ISSUE TITLE
Chronicle Queue JDK requirements

### ISSUE THREAD

**Issue by zoliszel** [OpenHFT/Chronicle-Queue#725]
Hi all,

we are looking to start a new project using Chronicle Queue and we also want to utilise a low latency collector in the same project. May I ask what version of the JDK is supported by CQ?  Do you guys support commercial VMs like Zing?

Thanks in advance,
Zoltan Szel

**Comment by peter-lawrey** [comment]
Hi, our supported Java versions are here, basically Java 8 and 11.
We don't support Zing but if you are going low garbage you may find Zing is slower as you don't benefit from it's concurrent collector.
We do support Azul Zulu.

https://github.com/OpenHFT/OpenHFT/blob/master/docs/Java-Version-Support.adoc

**Comment by minborg** [comment]
Have you considered ZGC and Java 15? Although not officially supported by Chronicle, this might be worth trying.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.20.42](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.20.42), [BOM-2.20.67](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.67)

**Comment by zoliszel** [comment]
ZGC and Java 15 seems a very plausible option. Thank you guys!

**Comment by SouthernYard** [comment]
Hi @peter-lawrey ,

Does that mean ZGC has the same concern? Which GC should I choose when I using the CQ?

Thanks,
Shawn

**Comment by dpisklov** [comment]
@SouthernYard ultimately it depends on what you are doing and what you are trying to achieve.
If you're writing ultra-low-latency zero GC code, any garbage collector will do, and ZGC (which basically disables GC) is also an option.
If you are writing normal software without strict latency requirements using Chronicle libraries for the execution speed - then you can choose whichever garbage collector works better for your scenario.

PS although we don't officially support Azul Zing, we have a client successfully running our code in Zing with no issues reported.

**Comment by SouthernYard** [comment]
Hi @dpisklov ,
I am also writing the ultra-low-latency zero GC application based on CQ. Ideally, we cannot avoid the GC totally although we try to save the objects out of the heap, we only decrease the GC frequency by this approach(like 1h -> 1day).
The ZGC/C4 can collect the garbage concurrently, and for Zing, it has the **ReadyNow** and **Pauseless** claims that there are good enhancements for JIT and GC. As @peter-lawrey  said:`if you are going low garbage you may find Zing is slower as you don't benefit from it's concurrent collector.`
Hence, I have two questions about this comment.
- Are all the efficiency of concurrent garbage collectors(like ZGC/C4) worse than some serial garbage collectors when the garbage collector works under this ultra-low-latency scenario?
- If yes for question 1, how can I avoid the stop-the-world of JVM when triggering the GC? LB or any other solutions?

Thanks,
Shawn

**Comment by dpisklov** [comment]
@SouthernYard 
1. Shawn, in our experience - yes, although the terminology isn't quite right - performance of garbage collector is OK, but performance of the JVM with concurrent GC is worse which ultimately is logical consequence of doing some work in the background as opposed to deferring most of it to the particular STW pauses.
2. One of the possible models is to make sure you have enough breathing room (i.e. young gen size) to survive you a whole "maintenance cycle" which can be a day or 5 days depending on your system's schedule. E.g. if you can restart your system every night - you just need to make sure you can get through the day without GCing, and then bounce the system instead of waiting for the GC, or may be if you only can restart once a week - make sure you can survive a week without GC. Or if your system is 24/7 you can do rolling restarts during the periods with the least activity with load balancer - options are nearly limitless.

**Comment by SouthernYard** [comment]
Hi @dpisklov ,

Cool, thanks a lot, let me learn a lot.

Thanks,
Shawn

**Comment by dpisklov** [comment]
@SouthernYard you're welcome!
