### ISSUE TITLE
writing metadata message as last message in queue does not always write EOF

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#823]
See net.openhft.chronicle.queue.ChronicleQueueIndexTest#checkTheEOFisWrittenToPreQueueFileWritingDocumentMetadata which fails consistently on Linux but works on Windows

**Comment by nicktindall** [comment]
I just ran it locally and the reason EOF doesn't appear is because the first cycle file is deleted when the second appender is acquired.
It happens somewhere in here `net.openhft.chronicle.queue.impl.single.SingleChronicleQueue#cleanupStoreFilesWithNoData`

**Comment by peter-lawrey** [comment]
That would explain the difference between the platforms as you can delete files in Linux at times that Windows prevents the deletion.

**Comment by rogersimmons** [comment]
Is there much real-world benefit to removing files with no data? For a file to exist something must have been written to it, and if the writePosition is 0 then that must have only been metadata, but this doesn't mean it's necessarily a candidate for removal (users could legitimately use metadata for purposes where deletion isn't appropriate in the absence of other data).

The simplest fix here is to remove the delete in cleanupStoreFilesWithNoData which then falls through to stamping EOF:
`if (store.writePosition() == 0 /**&& !store.file().delete()*/ && store.file().exists())`

In addition, further edge cases with EOF on pretouching and rolling have been identified by @JerryShea and @nicktindall. These are fixed by applying normaliseEOFs() on appender construction. The main overhead in doing this is already absorbed by the existing cleanupStoreFilesWithNoData check, so low overall impact in including in each appender construction.

Branch Issue822 (note, not 823) has been updated with both these fixes for review (and currently passes tests locally).

**Comment by JerryShea** [comment]
+1

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.21ea43](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.21ea43), [BOM-2.21ea110](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea110)
