### ISSUE TITLE
Reduced unwanted Object creation

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#922]
This relates to the following support issue -- https://support.chronicle.software/staff/ticket/422

The following is from a YourKit Dump

![image](https://user-images.githubusercontent.com/6506056/136580298-75685fc0-c3d2-4931-a9c0-20b61590d9a9.png)

**Comment by nicktindall** [comment]
Just shooting from the hip here, could this be related to the removal of the caching in that area, now we are ending up looking to the file system more often to see which cycles are there? I wonder if we could use a [WatchService](https://docs.oracle.com/javase/8/docs/api/java/nio/file/WatchService.html) to eliminate unnecessary directory listings (i.e. only refresh when there are changes)? or if that would also be garbage-y?

https://docs.oracle.com/javase/tutorial/essential/io/notification.html

**Comment by glukos** [comment]
@nicktindall 
I don't think we can get rid of scanning through queue directory, but WatchService is a good idea, thanks. We can trigger refresh only on WatchService event (ideally, only on removes) instead of doing it every minute.
Allocation burst on refresh is reproducible - all we need is creating enough queue files:
![image](https://user-images.githubusercontent.com/2736390/136844108-08d9e130-c7c1-4cf8-889a-24e4fef8d8f0.png)
I'll start with optimizing it

**Comment by JerryShea** [comment]
May be worth doing #913 while you are looking at this

**Comment by glukos** [comment]
@nicktindall @JerryShea @RobAustin 
Please see https://github.com/OpenHFT/Chronicle-Queue/pull/925.
I think the allocations issue is mostly resolved by the patch, but refresh operation is still CPU consuming (and may cause latency spikes). I've created a separate https://github.com/OpenHFT/Chronicle-Queue/issues/924 for using WatchService.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.21.92](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.21.92), [BOM-2.21.237](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21.237)
